---
language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
before_install:
  - git clone git://github.com/maxmind/geoip-api-c
  - cd geoip-api-c
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
script:
  - CFLAGS="-Werror -Wall -Wextra" python setup.py test
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "mNw9bQtM+fHITJiYGwex/YB42uy6IfIYSLQZWaD6F3mb2Y8aSXAtck+raV/C85CTM4LyBq6YyFLr1912+Xd0gmM7mSEQc5wXVf/vlzpMfNyDedonBSZeed7SGfm63xCTN9KWkOmhzIAhRy7WozmBP+bkNjyH9D1gYt863W6OYiA=\n"
